# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "QST Listing Workspace"
client_id = "f0517dd50928e4546916d0c07b379e87"
application_url = "https://qst-shopify-dashboard.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "read_products"
optional_scopes = []
use_legacy_install_flow = false

[access.admin]
embedded_app_direct_api_access = true
direct_api_mode = "online"

[auth]
redirect_urls = [
  "https://qst-shopify-dashboard.onrender.com/auth/callback"
]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
compliance_topics = ["customers/redact", "customers/data_request", "shop/redact"]
uri = "/webhooks"
